### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by zzj0402** [subramanyamdvss/UnsupNTS#3]
```
Traceback (most recent call last):
  File "predictions/noredund.py", line 23, in <module>
    main()
  File "predictions/noredund.py", line 8, in main
    for sent in fl:
  File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 913: ordinal not in range(128)
```

**Comment by saisuryadv** [comment]
Clearly the input file being used is not in ascii format, please try UTF-8 encoding.
